AllCops:
    NewCops: enable
    Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/*'

Style/Documentation:
    Enabled: false

Metrics/BlockLength:
    Exclude:
    - 'spec/**/*_spec.rb'
Lint/AmbiguousBlockAssociation:
    Exclude:
    - 'spec/**/*_spec.rb'
